### ISSUE TITLE
Unable to load the "Twig\Markdown\MarkdownRuntime" runtime.

### ISSUE THREAD

**Issue by codezm** [twigphp/markdown-extension#7]
I get some error "Unable to load the "Twig\Markdown\MarkdownRuntime" runtime.", what I should do that?

**Comment by raquinos** [comment]
When using outside Symfony framework (in my case it was Slim), you must also add a _runtime loader_ for instantiating `MarkdownRuntime` (which has the actual implementation of the filter), as stated on the [Twig documentation](https://twig.symfony.com/doc/2.x/advanced.html#definition-vs-runtime). 

A possible implementation is as follows:
```php
use Twig\Environment;
use Twig\Markdown\MarkdownExtension;
use Twig\RuntimeLoader\RuntimeLoaderInterface;
use Twig\Markdown\MarkdownRuntime;
use Twig\Markdown\DefaultMarkdown;

$twig = new Environment(...);
$twig->addExtension(new MarkdownExtension());

$view->getEnvironment()->addRuntimeLoader(new class implements RuntimeLoaderInterface {
    public function load($class) {
        // instantiate MarkdownRuntime with its required constructor argument
        if (MarkdownRuntime::class === $class) {
            return new MarkdownRuntime(new DefaultMarkdown());
        }
    }
});
```

**Comment by fabpot** [comment]
I've added some documentation about that in the README now.

**Comment by fabpot** [comment]
see f9aadd4
